export default [
  {
    title: 'Утренняя зарядка 10-15 мин',
    dates: [
      { date: 1, isDone: 'yes' },
      { date: 2, isDone: 'yes' },
      { date: 3, isDone: 'not' },
      { date: 4, isDone: 'yes' },
      { date: 5, isDone: 'yes' },
      { date: 6, isDone: 'not' },
      { date: 7, isDone: 'yes' },
      { date: 8, isDone: 'yes' },
      { date: 9, isDone: 'yes' },
      { date: 10, isDone: 'yes' },
    ],
  },
  {
    title: 'Замена сигарет на леденцы, орешки и т.п.',
    dates: [
      { date: 1, isDone: 'not' },
      { date: 2, isDone: 'yes' },
      { date: 3, isDone: 'not' },
      { date: 4, isDone: 'yes' },
      { date: 5, isDone: 'yes' },
      { date: 6, isDone: 'not' },
      { date: 7, isDone: 'yes' },
      { date: 8, isDone: 'yes' },
      { date: 9, isDone: 'yes' },
      { date: 10, isDone: 'not' },
    ],
  },
  {
    title: 'Читать минимум 30 мин в день',
    dates: [
      { date: 1, isDone: 'not' },
      { date: 2, isDone: 'not' },
      { date: 3, isDone: 'not' },
      { date: 4, isDone: 'not' },
      { date: 5, isDone: 'yes' },
      { date: 6, isDone: 'not' },
      { date: 7, isDone: 'not' },
      { date: 8, isDone: 'not' },
      { date: 9, isDone: 'not' },
      { date: 10, isDone: 'not' },
    ],
  },
];
